std_msgs/Header      header
int64       ts
uint8       controlMode
float32     brakePressure
float32     brakeSpeed
float32     targetBrakePressure
float32     targetBrakeSpeed
float32      targetBrakePosition
float32       brakePosition
bool 	    breakPedalOn
float32     breakMotorCurrent
uint8       breakErrorCode

float32     steerAngle
float32     steerSpeed
float32     targetSteerAngle
float32     targetSteerSpeed
float32     steerMotorTemperature
float32     steerMotorCurrent
float32	    steerTorque
float32     resultSetMiddleZero
uint8       steerErrorCode



float32     mainMotorSpeed
float32     mainMotorCurrent
uint8       motorBreakOn
float32     throtle
string      gear
float32     targetThrotle
string      targetGear
string      gearLeverPosition
bool       mainMotorBreakOn
uint8      throttleErrorCode
