(cl:in-package zf_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          LENGTH-VAL
          LENGTH
          MODE-VAL
          MODE
          TIME1-VAL
          TIME1
          TIME2-VAL
          TIME2
          NUM-VAL
          NUM
          LAT-VAL
          LAT
          LON-VAL
          LON
          HEIGHT-VAL
          HEIGHT
          V_N-VAL
          V_N
          V_E-VAL
          V_E
          V_EARTH-VAL
          V_EARTH
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          HEAD-VAL
          HEAD
          A_N-VAL
          A_N
          A_E-VAL
          A_E
          A_EARTH-VAL
          A_EARTH
          V_ROLL-VAL
          V_ROLL
          V_PITCH-VAL
          V_PITCH
          V_HEAD-VAL
          V_HEAD
          STATUS-VAL
          STATUS
          CHECKSUM-VAL
          CHECKSUM
))