// Generated by gencpp from file zf_msgs/pose2dArray.msg
// DO NOT EDIT!


#ifndef ZF_MSGS_MESSAGE_POSE2DARRAY_H
#define ZF_MSGS_MESSAGE_POSE2DARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose2D.h>

namespace zf_msgs
{
template <class ContainerAllocator>
struct pose2dArray_
{
  typedef pose2dArray_<ContainerAllocator> Type;

  pose2dArray_()
    : header()
    , points()  {
    }
  pose2dArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose2D_<ContainerAllocator> >::other >  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::zf_msgs::pose2dArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::zf_msgs::pose2dArray_<ContainerAllocator> const> ConstPtr;

}; // struct pose2dArray_

typedef ::zf_msgs::pose2dArray_<std::allocator<void> > pose2dArray;

typedef boost::shared_ptr< ::zf_msgs::pose2dArray > pose2dArrayPtr;
typedef boost::shared_ptr< ::zf_msgs::pose2dArray const> pose2dArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::zf_msgs::pose2dArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::zf_msgs::pose2dArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace zf_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'zf_msgs': ['/home/zf/xuechong_ws/zhuifengShow0919/src/zf_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::zf_msgs::pose2dArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zf_msgs::pose2dArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zf_msgs::pose2dArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zf_msgs::pose2dArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zf_msgs::pose2dArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zf_msgs::pose2dArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::zf_msgs::pose2dArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7fe16685deb9e41c592150dcf4ec62cb";
  }

  static const char* value(const ::zf_msgs::pose2dArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7fe16685deb9e41cULL;
  static const uint64_t static_value2 = 0x592150dcf4ec62cbULL;
};

template<class ContainerAllocator>
struct DataType< ::zf_msgs::pose2dArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "zf_msgs/pose2dArray";
  }

  static const char* value(const ::zf_msgs::pose2dArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::zf_msgs::pose2dArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
geometry_msgs/Pose2D[] points\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::zf_msgs::pose2dArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::zf_msgs::pose2dArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pose2dArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::zf_msgs::pose2dArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::zf_msgs::pose2dArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ZF_MSGS_MESSAGE_POSE2DARRAY_H
