// Generated by gencpp from file zfmsg/SteerStatus.msg
// DO NOT EDIT!


#ifndef ZFMSG_MESSAGE_STEERSTATUS_H
#define ZFMSG_MESSAGE_STEERSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace zfmsg
{
template <class ContainerAllocator>
struct SteerStatus_
{
  typedef SteerStatus_<ContainerAllocator> Type;

  SteerStatus_()
    : header()
    , ts(0)
    , angle(0.0)
    , speed(0.0)
    , controlMode(0)
    , targetAngle(0.0)
    , targetSpeed(0.0)
    , torque(0.0)
    , motorCurrent(0.0)
    , errorCode(0)  {
    }
  SteerStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ts(0)
    , angle(0.0)
    , speed(0.0)
    , controlMode(0)
    , targetAngle(0.0)
    , targetSpeed(0.0)
    , torque(0.0)
    , motorCurrent(0.0)
    , errorCode(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _ts_type;
  _ts_type ts;

   typedef float _angle_type;
  _angle_type angle;

   typedef float _speed_type;
  _speed_type speed;

   typedef uint8_t _controlMode_type;
  _controlMode_type controlMode;

   typedef float _targetAngle_type;
  _targetAngle_type targetAngle;

   typedef float _targetSpeed_type;
  _targetSpeed_type targetSpeed;

   typedef float _torque_type;
  _torque_type torque;

   typedef float _motorCurrent_type;
  _motorCurrent_type motorCurrent;

   typedef uint8_t _errorCode_type;
  _errorCode_type errorCode;





  typedef boost::shared_ptr< ::zfmsg::SteerStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::zfmsg::SteerStatus_<ContainerAllocator> const> ConstPtr;

}; // struct SteerStatus_

typedef ::zfmsg::SteerStatus_<std::allocator<void> > SteerStatus;

typedef boost::shared_ptr< ::zfmsg::SteerStatus > SteerStatusPtr;
typedef boost::shared_ptr< ::zfmsg::SteerStatus const> SteerStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::zfmsg::SteerStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::zfmsg::SteerStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace zfmsg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'zfmsg': ['/home/zf/xuechong_ws/zhuifengShow0919/src/zfmsg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::zfmsg::SteerStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::zfmsg::SteerStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zfmsg::SteerStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::zfmsg::SteerStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zfmsg::SteerStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::zfmsg::SteerStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::zfmsg::SteerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "09559d07e1ca45c09200d89a55db2635";
  }

  static const char* value(const ::zfmsg::SteerStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x09559d07e1ca45c0ULL;
  static const uint64_t static_value2 = 0x9200d89a55db2635ULL;
};

template<class ContainerAllocator>
struct DataType< ::zfmsg::SteerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "zfmsg/SteerStatus";
  }

  static const char* value(const ::zfmsg::SteerStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::zfmsg::SteerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header      header\n\
int64       ts\n\
float32     angle\n\
float32     speed\n\
uint8       controlMode\n\
float32     targetAngle\n\
float32     targetSpeed\n\
float32     torque\n\
float32     motorCurrent\n\
uint8       errorCode\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::zfmsg::SteerStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::zfmsg::SteerStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ts);
      stream.next(m.angle);
      stream.next(m.speed);
      stream.next(m.controlMode);
      stream.next(m.targetAngle);
      stream.next(m.targetSpeed);
      stream.next(m.torque);
      stream.next(m.motorCurrent);
      stream.next(m.errorCode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SteerStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::zfmsg::SteerStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::zfmsg::SteerStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ts: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ts);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "controlMode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.controlMode);
    s << indent << "targetAngle: ";
    Printer<float>::stream(s, indent + "  ", v.targetAngle);
    s << indent << "targetSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.targetSpeed);
    s << indent << "torque: ";
    Printer<float>::stream(s, indent + "  ", v.torque);
    s << indent << "motorCurrent: ";
    Printer<float>::stream(s, indent + "  ", v.motorCurrent);
    s << indent << "errorCode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.errorCode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ZFMSG_MESSAGE_STEERSTATUS_H
